// Builds the CISO alert / incident ticket export. A pure function so it can
// be tested without a database or an HTTP request — given the same
// investigation, signal, service, and actions, it always produces the same
// document.

import type { SignalMatch } from '@dcr/impact/exposure';

export interface TicketInvestigation {
  id: string;
  status: string;
  priority: 'P1' | 'P2' | 'P3' | 'informational' | null;
  risk_score: number | null;
  risk_components: Record<string, number> | null;
  escalated: boolean | null;
  escalation_reason: string | null;
  output: string | null;
  context: { match: SignalMatch } | null;
  created_at: string;
  ended_at: string | null;
}

export interface TicketSignal {
  external_id: string;
  source: string;
  provenance: string;
  title: string;
  vendor_project: string | null;
  product: string | null;
  published_at: string;
}

export interface TicketService {
  slug: string;
  name: string;
  department: string;
  criticality: string;
  resident_impact: string;
  impact_unit: string | null;
}

export interface TicketAction {
  rank: number;
  title: string;
  detail: string;
  sla: string;
  owner: string;
}

export interface TicketInput {
  investigation: TicketInvestigation;
  signal: TicketSignal;
  service: TicketService;
  actions: TicketAction[];
}

function narrativeOnly(output: string | null): string {
  if (!output) return '(investigation still in progress)';
  // Strip the trailing "---\n\n<marker>" footer for the ticket view — the
  // marker is an internal completion signal, not part of the readable
  // narrative a CISO or resident-facing report should show.
  return output.split(/\n\n---\n\n/)[0].trim();
}

export function buildIncidentTicketMarkdown(input: TicketInput): string {
  const { investigation, signal, service, actions } = input;
  const match = investigation.context?.match;
  const provenanceNote =
    signal.provenance === 'live'
      ? 'Live threat intelligence.'
      : 'Simulated for demonstration purposes.';

  const dependencyLine = match?.dependency
    ? `Reaches this service through a **${match.dependency.criticality}** dependency on **${match.dependency.infrastructure}** (${match.dependency.kind}). ${match.dependency.rationale}`
    : 'Directly affects this service\'s own technology.';

  const lines: string[] = [
    `# Incident Alert: ${service.name}`,
    '',
    `**Priority:** ${investigation.priority ?? 'unscored'}${investigation.escalated ? ' (escalated)' : ''}`,
    `**Risk score:** ${investigation.risk_score ?? 'n/a'}/100`,
    `**Department:** ${service.department}`,
    `**Generated:** ${investigation.ended_at ?? investigation.created_at}`,
    '',
    '## Signal',
    '',
    `- **${signal.external_id}** — ${signal.title}`,
    `- Source: ${signal.source} (${provenanceNote})`,
    `- Vendor / product: ${signal.vendor_project ?? 'n/a'} / ${signal.product ?? 'n/a'}`,
    `- Published: ${signal.published_at}`,
    '',
    '## Exposure',
    '',
    dependencyLine,
    '',
    '## Resident impact',
    '',
    service.resident_impact,
    ...(service.impact_unit ? [`\n_Measured in: ${service.impact_unit}_`] : []),
  ];

  if (investigation.escalated && investigation.escalation_reason) {
    lines.push('', '## Escalation', '', investigation.escalation_reason);
  }

  lines.push('', '## Investigation summary', '', narrativeOnly(investigation.output));

  if (actions.length > 0) {
    lines.push('', '## Recommended actions', '');
    for (const action of actions) {
      lines.push(`${action.rank}. **${action.title}** (${action.sla}, ${action.owner}) — ${action.detail}`);
    }
  }

  lines.push(
    '',
    '---',
    '',
    '_Generated by Detroit Cyber Ready. The exposure match above is deterministic and auditable; the summary and ' +
      'action plan were generated by an AI assistant from that match. Detroit\'s technology inventory in this demo ' +
      'is simulated — see the project README for what is real and what is simulated._'
  );

  return lines.join('\n');
}
